version: '3'
services:
  springboot-app-service: 
   container_name: springboot-app
   image: springboot-app 
   restart: always
   ports:
   - 8080:8080
   - 8081:8081

 
  mysql-service:
   container_name: mysql-server
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: root
    MYSQL_ROOT_PASSWORD: 
    MYSQL_ROOT_HOST: 'localhost'
   ports:
   - "3307:3307"
   restart: always